<a href="https://colab.research.google.com/github/vikasmahajan90/ML-29th/blob/master/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:

input=np.array([1,2,3,4])
def generate_matrix(input, n,increasing=False):
    if increasing:
        return np.array([ x**i for x in input for i in range(n)]).reshape(input.size,n)
    else:
        return np.array([ x**(n-1-i) for x in input for i in range(n)]).reshape(input.size,n)
print("============With List Comprehension==========")
print(generate_matrix(input, 3,True))
print(generate_matrix(input, 3,False))
# ====================================================

def generate_matrix_loop(input,n,increasing=False):
    arr=[]
    for x in input:
        for i in range(n):
            if increasing:
                arr.append(x**i)
            else:
                arr.append(x**(n-1-i))
    return np.array(arr).reshape(input.size,n)
print("============With Loop==========")
print(generate_matrix_loop(input, 3,True))
print(generate_matrix_loop(input, 3,False))

============With List Comprehension==========
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
============With Loop==========
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


In [4]:
# [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
input=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
move=len(input)+1-k
[sum(input[i:k+i])/k for i in range(move) ]

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]